### ISSUE TITLE
issue #1 Team Swallows

### ISSUE THREAD

**Issue by abdelp** [Emmanuelaaron/Enumerables#1]
- check the methods for acceptance of optional arguments or blocks E.g.: to count all the items that pass the condition with my_count method
- consider adding the acceptance of hashes to be equal to the original methods
- check the results of methods that depend on the length of the collection passed (E.g.: my_all?([]) should return true)

**Comment by Emmanuelaaron** [comment]
Thank you for pointing out this.
I have worked on everything that you pointed out
